name: Generate Snake

on:
  schedule:
    # Runs at 12:00 PM UTC every day
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@master
        with:
          github_user_name: alanledur1
          svg_out_path: dist/snake.svg

      - name: Upload the Snake animation
        uses: actions/upload-artifact@v4
        with:
          name: snake-activity
          path: dist/snake.svg
